# Generated by Django 5.1.4 on 2024-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.CharField(default='USER-DEFAULT', editable=False, max_length=50, null=True, unique=True),
        ),
    ]
