# Generated by Django 5.1.4 on 2024-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_person_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
