# Generated by Django 5.1.4 on 2024-12-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_person_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_id',
        ),
    ]
