# Generated by Django 5.1.4 on 2024-12-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_person_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'manager'), ('EMPLOYEE', 'employee')], default='EMPLOYEE', max_length=10),
        ),
    ]
